trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu latest
      steps:
      - task: Docker@2 #Build and Push Docker Image to DockerHub
        inputs:
          containerRegistry: 'yusuffranklin-docker-hub'
          repository: 'yusuffranklin/currency-exchange-devops'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
      - task: CopyFiles@2 #Copy Files to Staging Directory
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1 #Publish Artifact
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifests'
          publishLocation: 'Container'